pipeline {
  agent {
    docker {
      image 'thaott084/node-docker-cli:2.0' // Docker image bạn build
      args '-v /var/run/docker.sock:/var/run/docker.sock'
    }
  }

  environment {
    IMAGE_NAME = "thaott084/user-service"
    ENV_FILE = "/root/env-app/.env"
    SERVICE_DIR = "user-service"
  }

  stages {
    stage('Clone source') {
      steps {
        checkout scm
        dir("${SERVICE_DIR}") {
          sh 'ls -la'
        }
      }
    }

    stage('Install deps') {
      steps {
        dir("${SERVICE_DIR}") {
          sh 'npm install'
        }
      }
    }

    stage('Build') {
      steps {
        dir("${SERVICE_DIR}") {
          sh 'npm run build'
        }
      }
    }

    stage('Docker Build') {
      steps {
        dir("${SERVICE_DIR}") {
          script {
            def commit = sh(script: 'git rev-parse --short HEAD', returnStdout: true).trim()
            env.IMAGE_TAG = "${env.IMAGE_NAME}:build-${BUILD_NUMBER}-${commit}"
            sh 'docker build -t $IMAGE_TAG .'
          }
        }
      }
    }

    stage('Docker Push') {
      steps {
        sh 'docker push $IMAGE_TAG'
      }
    }
  }

  post {
    failure {
      echo '❌ Build failed'
    }
    success {
      echo '✅ Deploy thành công'
    }
  }
}
